/* ============================================================
   LE FOUR — Menu data & i18n dictionaries (FR / EN / AR)
   Prices: regular | large | box of 6 (from Menu Le Four 7 2026)
   ============================================================ */

const UI = {
  fr: {
    dir: 'ltr',
    boulangerie: 'Boulangerie',
    masthead: 'Beyrouth × Damas — Boulangerie libano-syrienne',
    tagline: 'Pétri de tradition. Servi avec élégance.',
    est: 'Cuit au feu de bois, chaque matin',
    heroCta: 'Consulter la carte',
    scrollHint: 'Découvrir',
    navCarte: 'La carte',
    navStory: 'Notre histoire',
    navManakish: 'Manakish',
    navPizzas: 'Pizzas',
    navMinis: 'Bouchées',
    navMezze: 'Mezzé',
    marquee: ['Créatif', 'Inspirant', 'Accueillant', 'Intemporel'],
    carteTitle: 'La Carte',
    carteNote: 'Servi tant que le four est chaud',
    indexLabel: 'Sommaire',
    pieces: 'spécialités',
    manakishTitle: 'Manakish',
    manakishSub: 'Cuites sur pierre, comme au pays.',
    pizzasTitle: 'Pizzas',
    pizzasSub: 'Quand Naples rencontre Damas.',
    minisTitle: 'Bouchées',
    minisSub: 'Par douzaine, à partager.',
    mezzeTitle: 'Mezzé',
    mezzeSub: 'À tremper, à partager.',
    drinksTitle: 'Boissons',
    drinksSub: 'Pour accompagner la fournée.',
    orderTitle: 'Commander en livraison',
    payTitle: 'Payer en ligne',
    contactTitle: 'Nous trouver',
    call: 'Appeler',
    directions: 'Itinéraire',
    hoursTitle: 'Horaires',
    follow: 'Suivez-nous',
    closed: 'Fermé',
    per12: 'la douzaine',
    sizeR: 'Régulier',
    sizeL: 'Sandwich',
    sizeB: 'Boîte de 6',
    close: 'Fermer',
    detail: 'Voir le détail',
    storyKicker: 'De Damas à Beyrouth',
    storyTitle: 'Plus qu’une boulangerie',
    story1: 'Le Four est une boulangerie libano-syrienne qui réunit les riches traditions culinaires de Beyrouth et de Damas. Inspirée des boulangeries de quartier qui rythment depuis toujours la vie du Levant, elle crée une expérience empreinte de chaleur, de nostalgie et d’authenticité.',
    story2: 'Des manakish fraîchement cuites aux fatayer et aux pains façonnés à la main, chaque produit est préparé avec soin, des ingrédients de qualité et un profond respect de l’héritage. Le Four est un lieu où les souvenirs se partagent, où les traditions se célèbrent — et où chaque bouchée raconte une histoire de chez nous.',
    quote: '« Pétri de tradition. Servi avec élégance. »',
    footerLine: 'Boulangerie libano-syrienne — manakish, fatayer & pizzas au feu de bois.',
    rights: 'Tous droits réservés.',
    veg: 'Végé',
    spicy: 'Épicé',
    sweet: 'Sucré',
    new: 'Nouveau',
  },
  en: {
    dir: 'ltr',
    boulangerie: 'Boulangerie',
    masthead: 'Beirut × Damascus — Lebanese-Syrian bakery',
    tagline: 'Crafted with tradition. Served with elegance.',
    est: 'Wood-fired, every morning',
    heroCta: 'View the menu',
    scrollHint: 'Discover',
    navCarte: 'The menu',
    navStory: 'Our story',
    navManakish: 'Manakish',
    navPizzas: 'Pizzas',
    navMinis: 'Minis',
    navMezze: 'Mezze',
    marquee: ['Creative', 'Inspiring', 'Welcoming', 'Timeless'],
    carteTitle: 'The Menu',
    carteNote: 'Served while the oven is hot',
    indexLabel: 'Contents',
    pieces: 'varieties',
    manakishTitle: 'Manakish',
    manakishSub: 'Stone-baked, just like back home.',
    pizzasTitle: 'Pizzas',
    pizzasSub: 'Where Naples meets Damascus.',
    minisTitle: 'Minis',
    minisSub: 'By the dozen, made to share.',
    mezzeTitle: 'Mezze',
    mezzeSub: 'To dip, to share.',
    drinksTitle: 'Drinks',
    drinksSub: 'To go with the bake.',
    orderTitle: 'Order delivery',
    payTitle: 'Pay online',
    contactTitle: 'Find us',
    call: 'Call',
    directions: 'Directions',
    hoursTitle: 'Hours',
    follow: 'Follow us',
    closed: 'Closed',
    per12: 'per dozen',
    sizeR: 'Regular',
    sizeL: 'Wrap',
    sizeB: 'Box of 6',
    close: 'Close',
    detail: 'View details',
    storyKicker: 'From Damascus to Beirut',
    storyTitle: 'More than a bakery',
    story1: 'Le Four is a Lebanese-Syrian bakery that brings together the rich culinary traditions of Beirut and Damascus. Inspired by the neighbourhood bakeries that have long been part of daily life across the Levant, it creates an experience filled with warmth, nostalgia and authenticity.',
    story2: 'From freshly baked manakish and fatayer to handcrafted breads, every product is made with care, quality ingredients and a deep respect for heritage. Le Four is a place where memories are shared, traditions are celebrated — and every bite tells a story from home.',
    quote: '“Crafted with tradition. Served with elegance.”',
    footerLine: 'Lebanese-Syrian bakery — wood-fired manakish, fatayer & pizzas.',
    rights: 'All rights reserved.',
    veg: 'Veggie',
    spicy: 'Spicy',
    sweet: 'Sweet',
    new: 'New',
  },
  ar: {
    dir: 'rtl',
    boulangerie: 'بولانجري',
    masthead: 'بيروت × دمشق — مخبز لبناني سوري',
    tagline: 'معجونٌ بالتقاليد، يُقدَّم بأناقة.',
    est: 'على نار الحطب، كل صباح',
    heroCta: 'تصفّح المنيو',
    scrollHint: 'اكتشف',
    navCarte: 'المنيو',
    navStory: 'حكايتنا',
    navManakish: 'مناقيش',
    navPizzas: 'بيتزا',
    navMinis: 'ميني',
    navMezze: 'مقبلات',
    marquee: ['إبداع', 'إلهام', 'ضيافة', 'أصالة'],
    carteTitle: 'المنيو',
    carteNote: 'يُقدَّم ما دام الفرن حاميًا',
    indexLabel: 'الفهرس',
    pieces: 'أصناف',
    manakishTitle: 'مناقيش',
    manakishSub: 'على الحجر، متل أيام الضيعة.',
    pizzasTitle: 'بيتزا',
    pizzasSub: 'حين تلتقي نابولي بدمشق.',
    minisTitle: 'ميني',
    minisSub: 'بالدزينة، للمشاركة.',
    mezzeTitle: 'مقبلات',
    mezzeSub: 'للغمس والمشاركة.',
    drinksTitle: 'مشروبات',
    drinksSub: 'لترافق خبزتك.',
    orderTitle: 'اطلب توصيل',
    payTitle: 'ادفع أونلاين',
    contactTitle: 'زورونا',
    call: 'اتصال',
    directions: 'الاتجاهات',
    hoursTitle: 'الدوام',
    follow: 'تابعونا',
    closed: 'مغلق',
    per12: 'للدزينة',
    sizeR: 'عادي',
    sizeL: 'سندويش',
    sizeB: 'علبة ٦ قطع',
    close: 'إغلاق',
    detail: 'التفاصيل',
    storyKicker: 'من دمشق إلى بيروت',
    storyTitle: 'أكثر من مجرد مخبز',
    story1: 'لو فور مخبزٌ لبناني–سوري يجمع بين التقاليد الغنيّة لمطبخَي بيروت ودمشق. مستوحى من أفران الحارة التي رافقت الحياة اليومية في بلاد الشام منذ الأزل، ليصنع تجربة مليئة بالدفء والحنين والأصالة.',
    story2: 'من المناقيش الطازجة إلى الفطائر والخبز المصنوع يدويًا، كل منتج يُحضَّر بعناية، بمكوّنات عالية الجودة واحترام عميق للتراث. لو فور مكانٌ تُتشارَك فيه الذكريات وتُحتفى فيه التقاليد — وكل لقمة تحكي حكاية من البيت.',
    quote: '«معجونٌ بالتقاليد، يُقدَّم بأناقة.»',
    footerLine: 'مخبز لبناني–سوري — مناقيش وفطائر وبيتزا على الحطب.',
    rights: 'جميع الحقوق محفوظة.',
    veg: 'نباتي',
    spicy: 'حار',
    sweet: 'حلو',
    new: 'جديد',
  },
};

/* art: shape (round|boat|triangle|bowl), topping style + palette keys for the
   procedural illustration generator in main.js */
const MENU = {
  manakish: [
    {
      id: 'zaatar', price: 4, large: 6, box: 18, tags: ['veg'],
      art: { shape: 'round', style: 'speckle', ink: '#46522A', accent: '#6E7A35' },
      name: { fr: 'Manouché Zaatar', en: 'Zaatar', ar: 'منقوشة زعتر' },
      desc: {
        fr: 'Pain plat levantin fraîchement cuit, garni d’un mélange traditionnel de zaatar, d’huile d’olive, de sumac et de graines de sésame grillées — une saveur riche et authentique, à la finition croustillante.',
        en: 'Freshly baked Levantine flatbread topped with a traditional blend of zaatar, olive oil, sumac and toasted sesame seeds — rich, authentic flavour with a crispy finish.',
        ar: 'خبز شامي طازج مغطّى بخلطة الزعتر التقليدية مع زيت الزيتون والسمّاق والسمسم المحمّص — نكهة غنيّة وأصيلة بقرمشة مثالية.',
      },
    },
    {
      id: 'zaatar-cheese', price: 6, large: 10, box: 30, tags: ['veg'],
      art: { shape: 'round', style: 'half', ink: '#46522A', accent: '#E7C979' },
      name: { fr: 'Zaatar & Fromage', en: 'Zaatar & Cheese', ar: 'زعتر وجبنة' },
      desc: {
        fr: 'Pain plat fraîchement cuit garni de zaatar parfumé et d’un délicat mélange de fromages orientaux, dont l’akkawi et le halloumi.',
        en: 'Freshly baked flatbread topped with aromatic zaatar and a refined blend of Eastern cheeses, including Akkawi and Halloumi.',
        ar: 'منقوشة طازجة بالزعتر العطري مع مزيج فاخر من الأجبان الشرقية، بينها العكاوي والحلّوم.',
      },
    },
    {
      id: 'cheese', price: 6, large: 10, box: 30, tags: ['veg'],
      art: { shape: 'round', style: 'melt', ink: '#D9A94E', accent: '#E7C979' },
      name: { fr: 'Manouché au Fromage', en: 'Cheese', ar: 'منقوشة جبنة' },
      desc: {
        fr: 'Pain artisanal cuit sur pierre, garni d’un élégant mélange de fromages orientaux haut de gamme — akkawi et halloumi fondus à la perfection.',
        en: 'Artisanal stone-baked flatbread topped with an elegant blend of premium Eastern cheeses, including Akkawi and Halloumi, melted to perfection.',
        ar: 'خبز حرفي على الحجر مع مزيج أنيق من أفخر الأجبان الشرقية — عكاوي وحلّوم ذائبان حتى الكمال.',
      },
    },
    {
      id: 'sujuk', price: 9, large: 14, tags: ['spicy'],
      art: { shape: 'round', style: 'discs', ink: '#6A2D34', accent: '#B96A4A' },
      name: { fr: 'Sujuk Affiné', en: 'Sujuk', ar: 'سجق' },
      desc: {
        fr: 'Pain plat cuit sur pierre garni de sujuk affiné de qualité supérieure, de fromages orientaux fondants, d’une riche sauce rouge maison et d’oignons caramélisés.',
        en: 'Stone-baked flatbread topped with premium aged sujuk, melted Eastern cheeses, rich house red sauce and caramelized onions.',
        ar: 'منقوشة على الحجر بسجق معتّق فاخر وأجبان شرقية ذائبة وصلصة حمراء منزلية غنية وبصل مكرمل.',
      },
    },
    {
      id: 'lahm-cheese', price: 6, large: 12, tags: [],
      art: { shape: 'round', style: 'mince-melt', ink: '#8A4A38', accent: '#E7C979' },
      name: { fr: 'Lahm bi Ajeen & Fromage', en: 'Lahm bi Ajeen & Cheese', ar: 'لحم بعجين وجبنة' },
      desc: {
        fr: 'Pain plat cuit sur pierre garni de viande hachée finement assaisonnée, de tomates, d’oignons, d’épices aromatiques et de fromages orientaux fondants.',
        en: 'Stone-baked flatbread topped with finely seasoned minced meat, tomatoes, onions, aromatic spices and melted Eastern cheeses.',
        ar: 'منقوشة على الحجر بلحمة مفرومة متبّلة بعناية مع البندورة والبصل والبهارات العطرية وأجبان شرقية ذائبة.',
      },
    },
    {
      id: 'lahm', price: 5.5, large: 10, box: 26, tags: [],
      art: { shape: 'round', style: 'mince', ink: '#8A4A38', accent: '#B96A4A' },
      name: { fr: 'Lahm bi Ajeen', en: 'Lahm bi Ajeen', ar: 'لحم بعجين' },
      desc: {
        fr: 'Pain plat cuit sur pierre garni de viande hachée finement assaisonnée, de tomates, d’oignons et d’épices du Moyen-Orient.',
        en: 'Stone-baked flatbread topped with finely seasoned minced meat, tomatoes, onions and aromatic Middle Eastern spices.',
        ar: 'منقوشة على الحجر بلحمة مفرومة متبّلة مع البندورة والبصل وبهارات شرقية عطرية.',
      },
    },
    {
      id: 'sfiha', price: 4, box: 18, tags: [],
      art: { shape: 'square', style: 'sfiha', ink: '#8A4A38', accent: '#6A2D34' },
      name: { fr: 'Sfiha à la Grenade', en: 'Sfiha Pomegranate', ar: 'صفيحة بدبس الرمان' },
      desc: {
        fr: 'Pain plat cuit sur pierre garni de viande hachée assaisonnée, d’oignons, d’épices aromatiques, de yogourt fermenté, d’une riche touche de mélasse de grenade et de pignons grillés.',
        en: 'Stone-baked flatbread topped with finely seasoned minced meat, onions, aromatic spices, cultured yogurt, a rich touch of pomegranate molasses and toasted pine nuts.',
        ar: 'صفيحة على الحجر بلحمة مفرومة متبّلة وبصل وبهارات ولبن مخمّر ولمسة غنية من دبس الرمان مع صنوبر محمّص.',
      },
    },
    {
      id: 'muhamara', price: 5, tags: ['veg', 'spicy'],
      art: { shape: 'round', style: 'spread', ink: '#B14A3A', accent: '#B96A4A' },
      name: { fr: 'Muhammara Syrienne', en: 'Muhammara', ar: 'محمرة' },
      desc: {
        fr: 'Pain artisanal garni d’un mélange syrien traditionnel de tomates, d’oignons, de poivrons doux et d’épices aromatiques.',
        en: 'Artisanal flatbread layered with a traditional Syrian blend of tomatoes, onions, sweet peppers and aromatic spices.',
        ar: 'خبز حرفي بخلطة سورية تقليدية من البندورة والبصل والفليفلة الحلوة والبهارات العطرية.',
      },
    },
    {
      id: 'muhamara-cheese', price: 7, large: 11, tags: ['veg', 'spicy'],
      art: { shape: 'round', style: 'spread-melt', ink: '#B14A3A', accent: '#E7C979' },
      name: { fr: 'Muhammara & Fromage', en: 'Muhammara & Cheese', ar: 'محمرة وجبنة' },
      desc: {
        fr: 'Pain artisanal garni d’un mélange syrien traditionnel de tomates, d’oignons, de poivrons doux, d’épices aromatiques et de fromages orientaux fondants.',
        en: 'Artisanal flatbread layered with a traditional Syrian blend of tomatoes, onions, sweet peppers, aromatic spices and melted Eastern cheeses.',
        ar: 'خبز حرفي بالخلطة السورية التقليدية من البندورة والبصل والفليفلة الحلوة والبهارات مع أجبان شرقية ذائبة.',
      },
    },
    {
      id: 'boat', price: 4, large: 14, box: 20, tags: ['veg'],
      art: { shape: 'boat', style: 'boat', ink: '#E7C979', accent: '#6E7A35' },
      name: { fr: 'Barque au Fromage Syrien', en: 'Syrian Cheese Boat', ar: 'قارب الجبنة السورية' },
      desc: {
        fr: 'Pain fraîchement cuit garni de fromage akkawi authentique, d’œufs, de persil, de beurre clarifié et de notre touche signature.',
        en: 'Freshly baked flatbread topped with authentic Akkawi cheese, eggs, parsley, clarified butter and our signature touch.',
        ar: 'خبز طازج على شكل قارب بجبنة عكاوي أصيلة وبيض وبقدونس وسمنة عربية — وبلمستنا الخاصة.',
      },
    },
    {
      id: 'spinach', price: 5, box: 22, tags: ['veg'],
      art: { shape: 'triangle', style: 'triangle', ink: '#46522A', accent: '#6A2D34' },
      name: { fr: 'Triangle aux Épinards', en: 'Spinach Triangle', ar: 'مثلث سبانخ' },
      desc: {
        fr: 'Triangle doré au four garni d’épinards, d’oignons, de noix, de graines de grenade, de sumac et d’épices méditerranéennes.',
        en: 'Golden baked triangle filled with spinach, onions, walnuts, pomegranate seeds, sumac and Mediterranean spices.',
        ar: 'مثلث مذهّب بالفرن محشو بالسبانخ والبصل والجوز وحب الرمان والسمّاق وبهارات متوسطية.',
      },
    },
    {
      id: 'spinach-cheese', price: 6, tags: ['veg'],
      art: { shape: 'triangle', style: 'triangle-melt', ink: '#46522A', accent: '#E7C979' },
      name: { fr: 'Épinards & Fromage', en: 'Spinach & Cheese', ar: 'سبانخ وجبنة' },
      desc: {
        fr: 'Pain doré au four garni d’épinards, d’oignons, de noix, de graines de grenade, de feta, du mélange de fromages Le Four, de sumac et d’épices méditerranéennes.',
        en: 'Golden baked flatbread filled with spinach, onions, walnuts, pomegranate seeds, feta, the Le Four cheese blend, sumac and Mediterranean spices.',
        ar: 'فطيرة مذهّبة بالسبانخ والبصل والجوز وحب الرمان وجبنة الفيتا وخلطة أجبان لو فور والسمّاق والبهارات المتوسطية.',
      },
    },
    {
      id: 'kishik', price: 6, tags: [],
      art: { shape: 'round', style: 'kishik', ink: '#D8C7A8', accent: '#B14A3A' },
      name: { fr: 'Kishik Traditionnel', en: 'Kishik', ar: 'كشك' },
      desc: {
        fr: 'Pain doré au four garni de kishk traditionnel, de tomates, d’oignons, d’huile d’olive et d’herbes méditerranéennes aromatiques.',
        en: 'Golden baked flatbread topped with traditional kishk, tomatoes, onions, olive oil and aromatic Mediterranean herbs.',
        ar: 'منقوشة مذهّبة بالكشك التقليدي والبندورة والبصل وزيت الزيتون والأعشاب المتوسطية العطرية.',
      },
    },
    {
      id: 'kawerma', price: 9, tags: [],
      art: { shape: 'round', style: 'kawerma', ink: '#7A4632', accent: '#E7C979' },
      name: { fr: 'Manouché Qawarma', en: 'Qawarma', ar: 'قاورما' },
      desc: {
        fr: 'Pain doré au four garni de qawarma de bœuf mijotée, d’œufs, de fromages orientaux fondants et d’épices aromatiques.',
        en: 'Golden baked flatbread topped with slow-cooked beef qawarma, eggs, melted Eastern cheeses and aromatic spices.',
        ar: 'منقوشة مذهّبة بقاورما اللحم البلدي المطهوّة ببطء مع البيض وأجبان شرقية ذائبة وبهارات عطرية.',
      },
    },
    {
      id: 'duplex', price: 10, tags: ['veg'],
      art: { shape: 'round', style: 'duplex', ink: '#46522A', accent: '#E7C979' },
      name: { fr: 'Duplex — Fromage & Zaatar', en: 'Duplex — Cheese & Zaatar', ar: 'دوبلكس — جبنة وزعتر' },
      desc: {
        fr: 'Pain doré au four farci de fromages orientaux fondants et couronné de zaatar traditionnel.',
        en: 'Golden baked flatbread stuffed with melted Eastern cheeses and finished with traditional zaatar on top.',
        ar: 'منقوشة مذهّبة محشوّة بالأجبان الشرقية الذائبة ومكلّلة بالزعتر التقليدي.',
      },
    },
    {
      id: 'chocobanana', price: 7, tags: ['sweet'],
      art: { shape: 'round', style: 'choco', ink: '#5C3A2E', accent: '#E7C979' },
      name: { fr: 'Choco-Banane', en: 'Choco Banana', ar: 'شوكو موز' },
      desc: {
        fr: 'Pain fraîchement cuit garni de chocolat fondant, de bananes fraîches, de crème de pistache et de noix grillées.',
        en: 'Freshly baked flatbread topped with melted chocolate, fresh bananas, pistachio cream and roasted nuts.',
        ar: 'منقوشة طازجة بالشوكولا الذائبة والموز الطازج وكريمة الفستق الحلبي والمكسرات المحمّصة.',
      },
    },
    {
      id: 'makdous', price: 10, tags: ['veg'],
      art: { shape: 'round', style: 'makdous', ink: '#6A2D34', accent: '#6E7A35' },
      name: { fr: 'Manouché au Makdous', en: 'Makdous', ar: 'مقدوس' },
      desc: {
        fr: 'Pain doré au four garni de makdous traditionnel, de labneh crémeux, de noix, d’huile d’olive, d’herbes méditerranéennes et de verdure du jardin Le Four.',
        en: 'Golden baked flatbread topped with traditional makdous, creamy labneh, walnuts, olive oil, aromatic Mediterranean herbs and Le Four garden greens.',
        ar: 'منقوشة مذهّبة بالمقدوس التقليدي واللبنة الكريمية والجوز وزيت الزيتون والأعشاب المتوسطية وخضار جنينة لو فور.',
      },
    },
    {
      id: 'sharhat', price: 15, tags: ['new'],
      art: { shape: 'round', style: 'sharhat', ink: '#7A4632', accent: '#6A2D34' },
      name: { fr: 'Manouché Sharhat', en: 'Sharhat', ar: 'شرحات' },
      desc: {
        fr: 'Deux couches de pain doré au four garnies de fines tranches de bœuf et d’agneau assaisonnées, mijotées lentement pour une saveur riche et authentique.',
        en: 'Two layers of golden baked flatbread filled with seasoned slices of beef and lamb, slowly cooked for a rich and authentic flavour.',
        ar: 'طبقتان من الخبز المذهّب محشوّتان بشرحات لحم البقر والغنم المتبّلة، مطهوّة ببطء لنكهة غنية وأصيلة.',
      },
    },
  ],

  pizzas: [
    {
      id: 'margherita', num: '01', tags: ['veg'],
      art: { style: 'pizza-margherita' },
      name: { fr: 'Margherita Classica', en: 'Margherita Classica', ar: 'مارغريتا كلاسيكا' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, basilic frais, parmesan et huile d’olive extra vierge.',
        en: 'San Marzano tomato sauce, fior di latte mozzarella, basil, parmesan and extra virgin olive oil.',
        ar: 'صلصة بندورة سان مارزانو، موزاريلا فيور دي لاتيه، ريحان طازج، بارميزان وزيت زيتون بكر.',
      },
    },
    {
      id: 'sujuk-napoli', num: '02', tags: ['spicy'],
      art: { style: 'pizza-sujuk' },
      name: { fr: 'Sujuk Affiné Napoli', en: 'Aged Sujuk Napoli', ar: 'سجق معتّق نابولي' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, sujuk affiné épicé, huile pimentée et basilic frais.',
        en: 'San Marzano tomato sauce, fior di latte, spicy aged sujuk, chili oil and basil.',
        ar: 'صلصة سان مارزانو، فيور دي لاتيه، سجق معتّق حار، زيت الفليفلة الحارة وريحان طازج.',
      },
    },
    {
      id: 'quattro', num: '03', tags: ['veg'],
      art: { style: 'pizza-quattro' },
      name: { fr: 'Quattro Formaggi', en: 'Quattro Formaggi', ar: 'كواترو فورماجي' },
      desc: {
        fr: 'Sauce blanche maison garnie d’un luxueux mélange de fior di latte, gorgonzola, parmesan et fromage fumé affiné.',
        en: 'House white sauce topped with a luxurious blend of fior di latte, gorgonzola, parmesan and aged smoked cheese.',
        ar: 'صلصة بيضاء منزلية مع مزيج فاخر من فيور دي لاتيه والغورغونزولا والبارميزان والجبنة المدخّنة المعتّقة.',
      },
    },
    {
      id: 'musakhan', num: '04', tags: [],
      art: { style: 'pizza-musakhan' },
      name: { fr: 'Musakhan Le Four', en: 'Le Four Musakhan', ar: 'مسخّن لو فور' },
      desc: {
        fr: 'Poulet au sumac, oignons caramélisés, fior di latte, pignons grillés et huile d’olive extra vierge.',
        en: 'Sumac-seasoned chicken, caramelized onions, fior di latte, roasted pine nuts and extra virgin olive oil.',
        ar: 'دجاج بالسمّاق، بصل مكرمل، فيور دي لاتيه، صنوبر محمّص وزيت زيتون بكر ممتاز.',
      },
    },
    {
      id: 'pastrami', num: '05', tags: [],
      art: { style: 'pizza-pastrami' },
      name: { fr: 'Pastrami Bab Touma', en: 'Bab Touma Pastrami', ar: 'باسطرما باب توما' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, pastrami premium, poivrons rouges rôtis, olives noires et oignons.',
        en: 'San Marzano tomato sauce, fior di latte, premium pastrami, roasted red peppers, black olives and onions.',
        ar: 'صلصة سان مارزانو، فيور دي لاتيه، باسطرما فاخرة، فليفلة حمراء مشوية، زيتون أسود وبصل.',
      },
    },
    {
      id: 'shawarma', num: '06', tags: [],
      art: { style: 'pizza-shawarma' },
      name: { fr: 'Shawarma Royale', en: 'Royal Shawarma', ar: 'شاورما رويال' },
      desc: {
        fr: 'Sauce BBQ, fior di latte, poulet shawarma, oignons, sauce à l’ail, mélasse de grenade et roquette fraîche.',
        en: 'BBQ sauce, fior di latte, shawarma chicken, onions, garlic sauce, pomegranate molasses and fresh arugula.',
        ar: 'صلصة باربكيو، فيور دي لاتيه، شاورما دجاج، بصل، ثومية، دبس رمان وجرجير طازج.',
      },
    },
    {
      id: 'damascus-night', num: '07', tags: ['veg'],
      art: { style: 'pizza-falafel' },
      name: { fr: 'Nuit de Damas', en: 'Damascus Night', ar: 'ليلة دمشقية' },
      desc: {
        fr: 'Sauce tahini, falafels croustillants, tomates, cornichons, sauce aux piments, tranches de citron, menthe fraîche et persil.',
        en: 'Tahini sauce, crispy falafel, tomatoes, pickles, pepper sauce, lemon slices, fresh mint and parsley.',
        ar: 'صلصة طحينة، فلافل مقرمشة، بندورة، كبيس، صلصة فليفلة، شرحات ليمون، نعناع طازج وبقدونس.',
      },
    },
    {
      id: 'garden', num: '08', tags: ['veg'],
      art: { style: 'pizza-garden' },
      name: { fr: 'Jardin Le Four', en: 'Le Four Garden', ar: 'جنينة لو فور' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, légumes grillés, olives, champignons et basilic.',
        en: 'San Marzano tomato sauce, fior di latte, grilled vegetables, olives, mushrooms and basil.',
        ar: 'صلصة سان مارزانو، فيور دي لاتيه، خضار مشوية، زيتون، فطر وريحان.',
      },
    },
    {
      id: 'bab-sharqi', num: '09', tags: [],
      art: { style: 'pizza-turkey' },
      name: { fr: 'Bab Sharqi', en: 'Bab Sharqi', ar: 'باب شرقي' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, champignons, artichauts, olives noires, dinde fumée et fromage fumé affiné.',
        en: 'San Marzano tomato sauce, fior di latte, mushrooms, artichokes, black olives, smoked turkey and aged smoked cheese.',
        ar: 'صلصة سان مارزانو، فيور دي لاتيه، فطر، أرضي شوكي، زيتون أسود، حبش مدخّن وجبنة مدخّنة معتّقة.',
      },
    },
    {
      id: 'marinara', num: '10', tags: ['veg'],
      art: { style: 'pizza-marinara' },
      name: { fr: 'De Damas à Napoli', en: 'Damas to Napoli', ar: 'من دمشق إلى نابولي' },
      desc: {
        fr: 'Sauce tomate San Marzano, ail frais, origan, basilic et huile d’olive extra vierge.',
        en: 'San Marzano tomato sauce, fresh garlic, oregano, basil and extra virgin olive oil.',
        ar: 'صلصة سان مارزانو، ثوم طازج، أوريغانو، ريحان وزيت زيتون بكر ممتاز.',
      },
    },
  ],

  minis: [
    { id: 'mini-spinach', price: 15, tags: ['veg'], art: { style: 'mini', ink: '#46522A' },
      name: { fr: 'Mini Épinards', en: 'Mini Spinach', ar: 'ميني سبانخ' },
      desc: { fr: 'Douze triangles d’épinards en format bouchée.', en: 'Twelve bite-size spinach triangles.', ar: 'اثنتا عشرة لقمة مثلثات سبانخ.' } },
    { id: 'mini-sfiha', price: 17, tags: [], art: { style: 'mini', ink: '#8A4A38' },
      name: { fr: 'Mini Sfiha', en: 'Mini Sfiha', ar: 'ميني صفيحة' },
      desc: { fr: 'Douze sfihas à la viande, dorées au four.', en: 'Twelve golden baked meat sfihas.', ar: 'اثنتا عشرة صفيحة لحمة مذهّبة بالفرن.' } },
    { id: 'mini-pizza', price: 15, tags: [], art: { style: 'mini', ink: '#B14A3A' },
      name: { fr: 'Mini Pizza', en: 'Mini Pizza', ar: 'ميني بيتزا' },
      desc: { fr: 'Douze petites pizzas moelleuses.', en: 'Twelve soft little pizzas.', ar: 'اثنتا عشرة بيتزا صغيرة هشّة.' } },
    { id: 'mini-sujuk', price: 18, tags: ['spicy'], art: { style: 'mini', ink: '#6A2D34' },
      name: { fr: 'Mini Sujuk', en: 'Mini Sujuk', ar: 'ميني سجق' },
      desc: { fr: 'Douze bouchées au sujuk épicé.', en: 'Twelve spicy sujuk bites.', ar: 'اثنتا عشرة لقمة بالسجق الحار.' } },
    { id: 'mini-musakhan', price: 17, tags: [], art: { style: 'mini', ink: '#B79B5B' },
      name: { fr: 'Mini Poulet Musakhan', en: 'Mini Chicken Musakhan', ar: 'ميني مسخّن دجاج' },
      desc: { fr: 'Douze rouleaux de poulet au sumac.', en: 'Twelve sumac chicken rolls.', ar: 'اثنتا عشرة لفافة دجاج بالسمّاق.' } },
    { id: 'mini-olive', price: 15, tags: ['veg'], art: { style: 'mini', ink: '#6E7A35' },
      name: { fr: 'Mini Olives', en: 'Mini Olive', ar: 'ميني زيتون' },
      desc: { fr: 'Douze bouchées aux olives du Levant.', en: 'Twelve Levantine olive bites.', ar: 'اثنتا عشرة لقمة بزيتون بلاد الشام.' } },
    { id: 'mini-cheese', price: 17, tags: ['veg'], art: { style: 'mini', ink: '#D9A94E' },
      name: { fr: 'Mini Fromage', en: 'Mini Cheese', ar: 'ميني جبنة' },
      desc: { fr: 'Douze bouchées au fromage fondant.', en: 'Twelve melty cheese bites.', ar: 'اثنتا عشرة لقمة بالجبنة الذائبة.' } },
    { id: 'mini-hotdog', price: 15, tags: [], art: { style: 'mini', ink: '#7A4632' },
      name: { fr: 'Mini Hot-Dog', en: 'Mini Hot Dog', ar: 'ميني هوت دوغ' },
      desc: { fr: 'Douze roulés moelleux au hot-dog.', en: 'Twelve soft hot dog rolls.', ar: 'اثنتا عشرة لفافة هوت دوغ طرية.' } },
  ],

  mezze: [
    { id: 'hummus', price: 7, tags: ['veg'], art: { style: 'bowl', ink: '#E8D9BD', accent: '#6E7A35' },
      name: { fr: 'Hommos', en: 'Hummus', ar: 'حمص' },
      desc: {
        fr: 'Purée de pois chiches onctueuse mélangée au tahini et au jus de citron frais, finie d’un filet d’huile d’olive extra vierge.',
        en: 'Creamy chickpea purée blended with tahini and fresh lemon juice, finished with extra virgin olive oil.',
        ar: 'حمص كريمي بالطحينة وعصير الليمون الطازج، مع رشّة زيت زيتون بكر ممتاز.',
      } },
    { id: 'mutabal', price: 9, tags: ['veg'], art: { style: 'bowl', ink: '#C9B9A6', accent: '#6A2D34' },
      name: { fr: 'Moutabal d’Aubergine', en: 'Eggplant Mutabal', ar: 'متبل باذنجان' },
      desc: {
        fr: 'Aubergine grillée au goût fumé, mélangée au tahini, au jus de citron frais et à l’huile d’olive extra vierge.',
        en: 'Smoky roasted eggplant blended with tahini, fresh lemon juice and extra virgin olive oil.',
        ar: 'باذنجان مشوي بنكهة مدخّنة مع الطحينة وعصير الليمون وزيت الزيتون البكر.',
      } },
    { id: 'muhamara-dip', price: 9, tags: ['veg', 'spicy'], art: { style: 'bowl', ink: '#B14A3A', accent: '#B79B5B' },
      name: { fr: 'Mouhammara', en: 'Muhammara', ar: 'محمرة' },
      desc: {
        fr: 'Riche mélange de poivrons rouges rôtis, de noix et de mélasse de grenade, fini d’un filet d’huile d’olive extra vierge.',
        en: 'A rich blend of roasted red peppers, walnuts and pomegranate molasses, finished with extra virgin olive oil.',
        ar: 'مزيج غني من الفليفلة الحمراء المشوية والجوز ودبس الرمان، مع لمسة زيت زيتون بكر.',
      } },
  ],

  drinks: [
    { id: 'cafe', price: null, tags: [], art: { style: 'cup' },
      name: { fr: 'Café', en: 'Coffee', ar: 'قهوة' },
      desc: { fr: 'Fraîchement préparé, à la façon du pays.', en: 'Freshly brewed, the way back home.', ar: 'محضّرة طازجة على الأصول.' } },
    { id: 'the', price: null, tags: [], art: { style: 'cup' },
      name: { fr: 'Thé', en: 'Tea', ar: 'شاي' },
      desc: { fr: 'Thé chaud infusé à la demande.', en: 'Hot tea brewed to order.', ar: 'شاي ساخن يُحضّر عند الطلب.' } },
    { id: 'ayran', price: null, tags: [], art: { style: 'glass' },
      name: { fr: 'Ayran', en: 'Ayran', ar: 'عيران' },
      desc: { fr: 'Boisson au yogourt, fraîche et légèrement salée.', en: 'Chilled yogurt drink, lightly salted.', ar: 'شراب اللبن المنعش بلمسة ملح.' } },
    { id: 'jus', price: null, tags: [], art: { style: 'bottle' },
      name: { fr: 'Jus', en: 'Juice', ar: 'عصير' },
      desc: { fr: 'Sélection de jus de fruits.', en: 'A selection of fruit juices.', ar: 'تشكيلة من عصائر الفواكه.' } },
    { id: 'soda', price: null, tags: [], art: { style: 'can' },
      name: { fr: 'Boisson gazeuse', en: 'Soft drink', ar: 'مشروب غازي' },
      desc: { fr: 'Sélection de boissons gazeuses.', en: 'A selection of soft drinks.', ar: 'تشكيلة من المشروبات الغازية.' } },
    { id: 'eau', price: null, tags: [], art: { style: 'bottle' },
      name: { fr: 'Eau', en: 'Water', ar: 'مياه' },
      desc: { fr: 'Eau de source ou pétillante.', en: 'Still or sparkling water.', ar: 'مياه عادية أو غازية.' } },
  ],
};

/* ── coordonnées & liens officiels (source unique) ───────── */
const INFO = {
  phoneDisplay: '(514) 624-3330',
  phoneRaw: '15146243330',
  whatsapp: '15146243330',
  email: 'info@lefourboulangerie.com',
  address: '15708 Boul. de Pierrefonds, Pierrefonds, QC H9H 3P6',
  maps: 'https://maps.app.goo.gl/gFnkbYyCMBkVqM2t5',
  uber: 'https://www.ubereats.com/ca/store/boulangerie-le-four/Sk5_leiLW6CDvsTvThUTWw',
  doordash: 'https://www.doordash.com/store/bakery-le-four-montreal-26133532/',
  instagram: 'https://www.instagram.com/lefourboulangerie/',
  facebook: 'https://www.facebook.com/boulangerielefour/',
  /* collez ici votre Stripe Payment Link (Dashboard → Payment Links)
     pour activer le bouton « Payer en ligne » : */
  stripe: '',
};

/* horaires (source : fiche publique — à confirmer par le client) */
const HOURS = [
  { d: { fr: 'Lundi', en: 'Monday', ar: 'الاثنين' }, h: null },
  { d: { fr: 'Mardi', en: 'Tuesday', ar: 'الثلاثاء' }, h: '06:30 – 18:00' },
  { d: { fr: 'Mercredi', en: 'Wednesday', ar: 'الأربعاء' }, h: '06:30 – 18:00' },
  { d: { fr: 'Jeudi', en: 'Thursday', ar: 'الخميس' }, h: '06:30 – 18:00' },
  { d: { fr: 'Vendredi', en: 'Friday', ar: 'الجمعة' }, h: '06:30 – 20:00' },
  { d: { fr: 'Samedi', en: 'Saturday', ar: 'السبت' }, h: '06:30 – 17:00' },
  { d: { fr: 'Dimanche', en: 'Sunday', ar: 'الأحد' }, h: '06:30 – 15:00' },
];
