/* ============================================================
   LE FOUR — Menu data & i18n dictionaries (FR / EN / AR)
   Prices: regular | large | box of 6 (from Menu Le Four 7 2026)
   ============================================================ */

const UI = {
  fr: {
    dir: 'ltr',
    boulangerie: 'Boulangerie',
    masthead: 'Beyrouth × Damas — Boulangerie libano-syrienne',
    tagline: 'Pétri de tradition. Servi avec élégance.',
    heroCta: 'Consulter la carte',
    scrollHint: 'Découvrir',
    navCarte: 'La carte',
    navStory: 'Notre histoire',
    navManakish: 'Manakish',
    navPizzas: 'Pizzas',
    navMinis: 'Bouchées',
    navMezze: 'Mezzé',
    marquee: ['Créatif', 'Inspirant', 'Accueillant', 'Intemporel'],
    carteTitle: 'La Carte',
    carteNote: 'Servi tant que le four est chaud',
    indexLabel: 'Sommaire',
    pieces: 'spécialités',
    manakishTitle: 'Manakish',
    manakishSub: 'Sorties du four, comme au pays.',
    pizzasTitle: 'Pizzas',
    pizzasSub: 'Quand Naples rencontre Damas.',
    minisTitle: 'Bouchées',
    minisSub: 'Par douzaine, parfait pour partager.',
    mezzeTitle: 'Mezzé',
    mezzeSub: 'À tremper, à partager.',
    drinksTitle: 'Boissons',
    drinksSub: 'Pour accompagner le tout.',
    orderTitle: 'Commander en ligne',
    contactTitle: 'Venez nous voir',
    call: 'Appeler',
    directions: 'Itinéraire',
    hoursTitle: 'Horaires',
    follow: 'Suivez-nous',
    closed: 'Fermé',
    galleryTitle: 'Chez nous',
    gallerySub: 'Quelques images de la boulangerie.',
    fItems: 'Choisissez vos articles',
    fNote: 'Une note pour nous ? (allergies, précisions…)',
    fPickHint: 'Faites défiler et ajustez les quantités',
    cartEmpty: 'Aucun article choisi',
    viewMenu: 'Voir le menu',
    orderOnline: 'Commander en ligne',
    orderHow: 'Comment voulez-vous commander ?',
    delivery: 'Livraison',
    pickup: 'Pour emporter',
    halal: '100 % halal',
    parking: 'Stationnement disponible sur place',
    statusOpen: 'Ouvert en ce moment',
    statusClosed: 'Fermé en ce moment',
    reviewCta: 'Laissez-nous un avis Google',
    cateringTitle: 'Traiteur',
    cateringSub: 'Vos événements, nos fournées. Dites-nous ce qu’il vous faut, on s’occupe du reste.',
    fName: 'Nom complet',
    fPhone: 'Téléphone',
    fDate: 'Date de l’événement',
    fGuests: 'Nombre de personnes',
    fDetails: 'Dites-nous ce qu’il vous faut (plats, quantités, allergies…)',
    fSend: 'Envoyer sur WhatsApp',
    per12: 'la douzaine',
    sizeR: 'Régulier',
    sizeL: 'Sandwich',
    sizeB: 'Boîte de 6',
    close: 'Fermer',
    detail: 'Voir le détail',
    storyKicker: 'De Damas à Beyrouth',
    storyTitle: 'Plus qu’une boulangerie',
    story1: 'Le Four, c’est une boulangerie libano-syrienne qui réunit les traditions de Beyrouth et de Damas. On s’inspire des boulangeries de quartier du Levant — celles où tout le monde passe le matin — pour en ramener un peu de cette chaleur ici, à Pierrefonds.',
    story2: 'Des manakish fraîches aux fatayer et aux pains faits à la main, tout est préparé le matin même, avec de bons ingrédients et beaucoup de respect pour la tradition. Et tout, sans exception, est halal.',
    quote: '« Pétri de tradition. Servi avec élégance. »',
    footerLine: 'Boulangerie libano-syrienne — manakish, fatayer & bouchées. Tout est 100 % halal.',
    rights: 'Tous droits réservés.',
    veg: 'Végé',
    spicy: 'Épicé',
    sweet: 'Sucré',
    new: 'Nouveau',
  },
  en: {
    dir: 'ltr',
    boulangerie: 'Boulangerie',
    masthead: 'Beirut × Damascus — Lebanese-Syrian bakery',
    tagline: 'Crafted with tradition. Served with elegance.',
    heroCta: 'View the menu',
    scrollHint: 'Discover',
    navCarte: 'The menu',
    navStory: 'Our story',
    navManakish: 'Manakish',
    navPizzas: 'Pizzas',
    navMinis: 'Minis',
    navMezze: 'Mezze',
    marquee: ['Creative', 'Inspiring', 'Welcoming', 'Timeless'],
    carteTitle: 'The Menu',
    carteNote: 'Served while the oven is hot',
    indexLabel: 'Contents',
    pieces: 'varieties',
    manakishTitle: 'Manakish',
    manakishSub: 'Stone-baked, just like back home.',
    pizzasTitle: 'Pizzas',
    pizzasSub: 'Where Naples meets Damascus.',
    minisTitle: 'Minis',
    minisSub: 'By the dozen, made to share.',
    mezzeTitle: 'Mezze',
    mezzeSub: 'To dip, to share.',
    drinksTitle: 'Drinks',
    drinksSub: 'To go with your order.',
    orderTitle: 'Order online',
    contactTitle: 'Find us',
    call: 'Call',
    directions: 'Directions',
    hoursTitle: 'Hours',
    follow: 'Follow us',
    closed: 'Closed',
    galleryTitle: 'Our place',
    gallerySub: 'A few pictures from the bakery.',
    fItems: 'Choose your items',
    fNote: 'A note for us? (allergies, details…)',
    fPickHint: 'Scroll and set the quantities',
    cartEmpty: 'No items selected',
    viewMenu: 'View the menu',
    orderOnline: 'Order online',
    orderHow: 'How would you like to order?',
    delivery: 'Delivery',
    pickup: 'Pickup',
    halal: '100% halal',
    parking: 'Parking available on site',
    statusOpen: 'Open right now',
    statusClosed: 'Closed right now',
    reviewCta: 'Leave us a Google review',
    cateringTitle: 'Catering',
    cateringSub: 'Your events, our ovens — we take care of the rest.',
    fName: 'Full name',
    fPhone: 'Phone',
    fDate: 'Event date',
    fGuests: 'Number of guests',
    fDetails: 'Tell us what you need (items, quantities, allergies…)',
    fSend: 'Send on WhatsApp',
    per12: 'per dozen',
    sizeR: 'Regular',
    sizeL: 'Wrap',
    sizeB: 'Box of 6',
    close: 'Close',
    detail: 'View details',
    storyKicker: 'From Damascus to Beirut',
    storyTitle: 'More than a bakery',
    story1: 'Le Four is a Lebanese-Syrian bakery that brings together the rich culinary traditions of Beirut and Damascus. Inspired by the neighbourhood bakeries that have long been part of daily life across the Levant, it creates an experience filled with warmth, nostalgia and authenticity.',
    story2: 'From fresh manakish and fatayer to hand-shaped breads, everything is made the same morning, with good ingredients and deep respect for tradition. And everything, without exception, is halal.',
    quote: '“Crafted with tradition. Served with elegance.”',
    footerLine: 'Lebanese-Syrian bakery — manakish, fatayer & bites. Everything is 100% halal.',
    rights: 'All rights reserved.',
    veg: 'Veggie',
    spicy: 'Spicy',
    sweet: 'Sweet',
    new: 'New',
  },
  ar: {
    dir: 'rtl',
    boulangerie: 'بولانجري',
    masthead: 'بيروت × دمشق — مخبز لبناني سوري',
    tagline: 'معجونٌ بالتقاليد، يُقدَّم بأناقة.',
    heroCta: 'تصفّح المنيو',
    scrollHint: 'اكتشف',
    navCarte: 'المنيو',
    navStory: 'حكايتنا',
    navManakish: 'مناقيش',
    navPizzas: 'بيتزا',
    navMinis: 'ميني',
    navMezze: 'مقبلات',
    marquee: ['إبداع', 'إلهام', 'ضيافة', 'أصالة'],
    carteTitle: 'المنيو',
    carteNote: 'يُقدَّم ما دام الفرن حاميًا',
    indexLabel: 'الفهرس',
    pieces: 'أصناف',
    manakishTitle: 'مناقيش',
    manakishSub: 'على الحجر، متل أيام الضيعة.',
    pizzasTitle: 'بيتزا',
    pizzasSub: 'حين تلتقي نابولي بدمشق.',
    minisTitle: 'ميني',
    minisSub: 'بالدزينة، للمشاركة.',
    mezzeTitle: 'مقبلات',
    mezzeSub: 'للغمس والمشاركة.',
    drinksTitle: 'مشروبات',
    drinksSub: 'لترافق طلبك.',
    orderTitle: 'اطلب أونلاين',
    contactTitle: 'زورونا',
    call: 'اتصال',
    directions: 'الاتجاهات',
    hoursTitle: 'الدوام',
    follow: 'تابعونا',
    closed: 'مغلق',
    galleryTitle: 'من عنا',
    gallerySub: 'صور من داخل المخبز.',
    fItems: 'اختر الأصناف',
    fNote: 'في ملاحظة إلنا؟ (حساسية، تفاصيل…)',
    fPickHint: 'مرّر واختر الكميات',
    cartEmpty: 'ما في أصناف مختارة',
    viewMenu: 'تصفّح المنيو',
    orderOnline: 'اطلب أونلاين',
    orderHow: 'كيف بتحب تطلب؟',
    delivery: 'توصيل',
    pickup: 'استلام من المحل',
    halal: '100٪ حلال',
    parking: 'موقف سيارات متوفر بالموقع',
    statusOpen: 'مفتوح حاليًا',
    statusClosed: 'مغلق حاليًا',
    reviewCta: 'قيّمنا على Google',
    cateringTitle: 'كاترينغ',
    cateringSub: 'مناسباتكم علينا — منجهّزلكم كل شي.',
    fName: 'الاسم الكامل',
    fPhone: 'رقم الهاتف',
    fDate: 'تاريخ المناسبة',
    fGuests: 'عدد الأشخاص',
    fDetails: 'خبّرنا شو بتحتاج (أصناف، كميات، حساسية…)',
    fSend: 'إرسال عبر واتساب',
    per12: 'للدزينة',
    sizeR: 'عادي',
    sizeL: 'سندويش',
    sizeB: 'علبة ٦ قطع',
    close: 'إغلاق',
    detail: 'التفاصيل',
    storyKicker: 'من دمشق إلى بيروت',
    storyTitle: 'أكثر من مجرد مخبز',
    story1: 'لو فور مخبزٌ لبناني–سوري يجمع بين التقاليد الغنيّة لمطبخَي بيروت ودمشق. مستوحى من أفران الحارة التي رافقت الحياة اليومية في بلاد الشام منذ الأزل، ليصنع تجربة مليئة بالدفء والحنين والأصالة.',
    story2: 'من المناقيش الطازجة إلى الفطائر والخبز المصنوع يدويًا، كل شي منحضّرو بنفس الصباح، بمكوّنات منيحة واحترام كبير للتقاليد. وكل شي عنا — بدون استثناء — حلال.',
    quote: '«معجونٌ بالتقاليد، يُقدَّم بأناقة.»',
    footerLine: 'مخبز لبناني–سوري — مناقيش وفطائر ولقيمات. كل شي عنا 100٪ حلال.',
    rights: 'جميع الحقوق محفوظة.',
    veg: 'نباتي',
    spicy: 'حار',
    sweet: 'حلو',
    new: 'جديد',
  },
};

/* art: shape (round|boat|triangle|bowl), topping style + palette keys for the
   procedural illustration generator in main.js */
const MENU = {
  manakish: [
    {
      id: 'zaatar', price: 4, large: 6, box: 18, tags: ['veg'],
      art: { shape: 'round', style: 'speckle', ink: '#46522A', accent: '#6E7A35' },
      name: { fr: 'Manouché Zaatar', en: 'Zaatar', ar: 'منقوشة زعتر' },
      desc: {
        fr: 'Notre pâte fraîche du matin, garnie de zaatar, d’huile d’olive, de sumac et de sésame grillé. Croustillante sur les bords, moelleuse au centre.',
        en: 'Freshly baked Levantine flatbread topped with a traditional blend of zaatar, olive oil, sumac and toasted sesame seeds — rich, authentic flavour with a crispy finish.',
        ar: 'خبز شامي طازج مغطّى بخلطة الزعتر التقليدية مع زيت الزيتون والسمّاق والسمسم المحمّص — نكهة غنيّة وأصيلة بقرمشة مثالية.',
      },
    },
    {
      id: 'zaatar-cheese', price: 6, large: 10, box: 30, tags: ['veg'],
      art: { shape: 'round', style: 'half', ink: '#46522A', accent: '#E7C979' },
      name: { fr: 'Zaatar & Fromage', en: 'Zaatar & Cheese', ar: 'زعتر وجبنة' },
      desc: {
        fr: 'Le classique au zaatar, avec notre mélange de fromages akkawi et halloumi qui fond par-dessus.',
        en: 'Freshly baked flatbread topped with aromatic zaatar and a refined blend of Eastern cheeses, including Akkawi and Halloumi.',
        ar: 'منقوشة طازجة بالزعتر العطري مع مزيج فاخر من الأجبان الشرقية، بينها العكاوي والحلّوم.',
      },
    },
    {
      id: 'cheese', price: 6, large: 10, box: 30, tags: ['veg'],
      art: { shape: 'round', style: 'melt', ink: '#D9A94E', accent: '#E7C979' },
      name: { fr: 'Manouché au Fromage', en: 'Cheese', ar: 'منقوشة جبنة' },
      desc: {
        fr: 'Un mélange généreux de fromages akkawi et halloumi, fondu juste comme il faut. Simple et parfait.',
        en: 'Artisanal stone-baked flatbread topped with an elegant blend of premium Eastern cheeses, including Akkawi and Halloumi, melted to perfection.',
        ar: 'خبز حرفي على الحجر مع مزيج أنيق من أفخر الأجبان الشرقية — عكاوي وحلّوم ذائبان حتى الكمال.',
      },
    },
    {
      id: 'sujuk', price: 9, large: 14, tags: ['spicy'],
      art: { shape: 'round', style: 'discs', ink: '#6A2D34', accent: '#B96A4A' },
      name: { fr: 'Sujuk Affiné', en: 'Sujuk', ar: 'سجق' },
      desc: {
        fr: 'Saucisse sujuk bien relevée, fromages fondants, sauce maison et oignons caramélisés. Ça réveille.',
        en: 'Stone-baked flatbread topped with premium aged sujuk, melted Eastern cheeses, rich house red sauce and caramelized onions.',
        ar: 'منقوشة على الحجر بسجق معتّق فاخر وأجبان شرقية ذائبة وصلصة حمراء منزلية غنية وبصل مكرمل.',
      },
    },
    {
      id: 'lahm-cheese', price: 6, large: 12, tags: [],
      art: { shape: 'round', style: 'mince-melt', ink: '#8A4A38', accent: '#E7C979' },
      name: { fr: 'Lahm bi Ajeen & Fromage', en: 'Lahm bi Ajeen & Cheese', ar: 'لحم بعجين وجبنة' },
      desc: {
        fr: 'Bœuf haché assaisonné avec tomates, oignons et épices, plus du fromage fondant par-dessus.',
        en: 'Stone-baked flatbread topped with finely seasoned minced meat, tomatoes, onions, aromatic spices and melted Eastern cheeses.',
        ar: 'منقوشة على الحجر بلحمة مفرومة متبّلة بعناية مع البندورة والبصل والبهارات العطرية وأجبان شرقية ذائبة.',
      },
    },
    {
      id: 'lahm', price: 5.5, large: 10, box: 26, tags: [],
      art: { shape: 'round', style: 'mince', ink: '#8A4A38', accent: '#B96A4A' },
      name: { fr: 'Lahm bi Ajeen', en: 'Lahm bi Ajeen', ar: 'لحم بعجين' },
      desc: {
        fr: 'Bœuf haché assaisonné, tomates, oignons et nos épices. Le classique qu’on mange depuis toujours.',
        en: 'Stone-baked flatbread topped with finely seasoned minced meat, tomatoes, onions and aromatic Middle Eastern spices.',
        ar: 'منقوشة على الحجر بلحمة مفرومة متبّلة مع البندورة والبصل وبهارات شرقية عطرية.',
      },
    },
    {
      id: 'sfiha', price: 4, box: 18, tags: [],
      art: { shape: 'square', style: 'sfiha', ink: '#8A4A38', accent: '#6A2D34' },
      name: { fr: 'Sfiha à la Grenade', en: 'Sfiha Pomegranate', ar: 'صفيحة بدبس الرمان' },
      desc: {
        fr: 'Bœuf haché, oignons, yogourt et épices, avec une touche de mélasse de grenade et des pignons grillés.',
        en: 'Stone-baked flatbread topped with finely seasoned minced meat, onions, aromatic spices, cultured yogurt, a rich touch of pomegranate molasses and toasted pine nuts.',
        ar: 'صفيحة على الحجر بلحمة مفرومة متبّلة وبصل وبهارات ولبن مخمّر ولمسة غنية من دبس الرمان مع صنوبر محمّص.',
      },
    },
    {
      id: 'muhamara', price: 5, tags: ['veg', 'spicy'],
      art: { shape: 'round', style: 'spread', ink: '#B14A3A', accent: '#B96A4A' },
      name: { fr: 'Muhammara Syrienne', en: 'Muhammara', ar: 'محمرة' },
      desc: {
        fr: 'Notre mélange syrien de tomates, oignons, poivrons doux et épices. Végé et plein de goût.',
        en: 'Artisanal flatbread layered with a traditional Syrian blend of tomatoes, onions, sweet peppers and aromatic spices.',
        ar: 'خبز حرفي بخلطة سورية تقليدية من البندورة والبصل والفليفلة الحلوة والبهارات العطرية.',
      },
    },
    {
      id: 'muhamara-cheese', price: 7, large: 11, tags: ['veg', 'spicy'],
      art: { shape: 'round', style: 'spread-melt', ink: '#B14A3A', accent: '#E7C979' },
      name: { fr: 'Muhammara & Fromage', en: 'Muhammara & Cheese', ar: 'محمرة وجبنة' },
      desc: {
        fr: 'Le même mélange muhammara, avec du fromage fondant par-dessus.',
        en: 'Artisanal flatbread layered with a traditional Syrian blend of tomatoes, onions, sweet peppers, aromatic spices and melted Eastern cheeses.',
        ar: 'خبز حرفي بالخلطة السورية التقليدية من البندورة والبصل والفليفلة الحلوة والبهارات مع أجبان شرقية ذائبة.',
      },
    },
    {
      id: 'boat', price: 4, large: 14, box: 20, tags: ['veg'],
      art: { shape: 'boat', style: 'boat', ink: '#E7C979', accent: '#6E7A35' },
      name: { fr: 'Barque au Fromage Syrien', en: 'Syrian Cheese Boat', ar: 'قارب الجبنة السورية' },
      desc: {
        fr: 'En forme de barque, garnie de fromage akkawi, d’un œuf, de persil et de beurre clarifié.',
        en: 'Freshly baked flatbread topped with authentic Akkawi cheese, eggs, parsley, clarified butter and our signature touch.',
        ar: 'خبز طازج على شكل قارب بجبنة عكاوي أصيلة وبيض وبقدونس وسمنة عربية — وبلمستنا الخاصة.',
      },
    },
    {
      id: 'spinach', price: 5, box: 22, tags: ['veg'],
      art: { shape: 'triangle', style: 'triangle', ink: '#46522A', accent: '#6A2D34' },
      name: { fr: 'Triangle aux Épinards', en: 'Spinach Triangle', ar: 'مثلث سبانخ' },
      desc: {
        fr: 'Épinards, oignons, noix, grains de grenade et sumac, repliés en triangle bien doré.',
        en: 'Golden baked triangle filled with spinach, onions, walnuts, pomegranate seeds, sumac and Mediterranean spices.',
        ar: 'مثلث مذهّب بالفرن محشو بالسبانخ والبصل والجوز وحب الرمان والسمّاق وبهارات متوسطية.',
      },
    },
    {
      id: 'spinach-cheese', price: 6, tags: ['veg'],
      art: { shape: 'triangle', style: 'triangle-melt', ink: '#46522A', accent: '#E7C979' },
      name: { fr: 'Épinards & Fromage', en: 'Spinach & Cheese', ar: 'سبانخ وجبنة' },
      desc: {
        fr: 'Nos épinards avec de la feta et notre mélange de fromages, dorés au four.',
        en: 'Golden baked flatbread filled with spinach, onions, walnuts, pomegranate seeds, feta, the Le Four cheese blend, sumac and Mediterranean spices.',
        ar: 'فطيرة مذهّبة بالسبانخ والبصل والجوز وحب الرمان وجبنة الفيتا وخلطة أجبان لو فور والسمّاق والبهارات المتوسطية.',
      },
    },
    {
      id: 'kishik', price: 6, tags: [],
      art: { shape: 'round', style: 'kishik', ink: '#D8C7A8', accent: '#B14A3A' },
      name: { fr: 'Kishik Traditionnel', en: 'Kishik', ar: 'كشك' },
      desc: {
        fr: 'Kishk traditionnel avec tomates, oignons, huile d’olive et fines herbes.',
        en: 'Golden baked flatbread topped with traditional kishk, tomatoes, onions, olive oil and aromatic Mediterranean herbs.',
        ar: 'منقوشة مذهّبة بالكشك التقليدي والبندورة والبصل وزيت الزيتون والأعشاب المتوسطية العطرية.',
      },
    },
    {
      id: 'kawerma', price: 9, tags: [],
      art: { shape: 'round', style: 'kawerma', ink: '#7A4632', accent: '#E7C979' },
      name: { fr: 'Manouché Qawarma', en: 'Qawarma', ar: 'قاورما' },
      desc: {
        fr: 'Qawarma de bœuf mijoté, œufs et fromages fondants. Un déjeuner qui tient au corps.',
        en: 'Golden baked flatbread topped with slow-cooked beef qawarma, eggs, melted Eastern cheeses and aromatic spices.',
        ar: 'منقوشة مذهّبة بقاورما اللحم البلدي المطهوّة ببطء مع البيض وأجبان شرقية ذائبة وبهارات عطرية.',
      },
    },
    {
      id: 'duplex', price: 10, tags: ['veg'],
      art: { shape: 'round', style: 'duplex', ink: '#46522A', accent: '#E7C979' },
      name: { fr: 'Duplex — Fromage & Zaatar', en: 'Duplex — Cheese & Zaatar', ar: 'دوبلكس — جبنة وزعتر' },
      desc: {
        fr: 'Deux étages : du fromage fondant en dedans, du zaatar sur le dessus.',
        en: 'Golden baked flatbread stuffed with melted Eastern cheeses and finished with traditional zaatar on top.',
        ar: 'منقوشة مذهّبة محشوّة بالأجبان الشرقية الذائبة ومكلّلة بالزعتر التقليدي.',
      },
    },
    {
      id: 'chocobanana', price: 7, tags: ['sweet'],
      art: { shape: 'round', style: 'choco', ink: '#5C3A2E', accent: '#E7C979' },
      name: { fr: 'Choco-Banane', en: 'Choco Banana', ar: 'شوكو موز' },
      desc: {
        fr: 'Chocolat fondant, banane fraîche, crème de pistache et noix grillées. Pour les becs sucrés.',
        en: 'Freshly baked flatbread topped with melted chocolate, fresh bananas, pistachio cream and roasted nuts.',
        ar: 'منقوشة طازجة بالشوكولا الذائبة والموز الطازج وكريمة الفستق الحلبي والمكسرات المحمّصة.',
      },
    },
    {
      id: 'makdous', price: 10, tags: ['veg'],
      art: { shape: 'round', style: 'makdous', ink: '#6A2D34', accent: '#6E7A35' },
      name: { fr: 'Manouché au Makdous', en: 'Makdous', ar: 'مقدوس' },
      desc: {
        fr: 'Makdous maison, labneh crémeux, noix, huile d’olive et un peu de verdure.',
        en: 'Golden baked flatbread topped with traditional makdous, creamy labneh, walnuts, olive oil, aromatic Mediterranean herbs and Le Four garden greens.',
        ar: 'منقوشة مذهّبة بالمقدوس التقليدي واللبنة الكريمية والجوز وزيت الزيتون والأعشاب المتوسطية وخضار جنينة لو فور.',
      },
    },
    {
      id: 'sharhat', price: 15, tags: ['new'],
      art: { shape: 'round', style: 'sharhat', ink: '#7A4632', accent: '#6A2D34' },
      name: { fr: 'Manouché Sharhat', en: 'Sharhat', ar: 'شرحات' },
      desc: {
        fr: 'Deux pains garnis de fines tranches de bœuf et d’agneau mijotées lentement. Notre nouveauté.',
        en: 'Two layers of golden baked flatbread filled with seasoned slices of beef and lamb, slowly cooked for a rich and authentic flavour.',
        ar: 'طبقتان من الخبز المذهّب محشوّتان بشرحات لحم البقر والغنم المتبّلة، مطهوّة ببطء لنكهة غنية وأصيلة.',
      },
    },
  ],

  pizzas: [
    {
      id: 'margherita', num: '01', tags: ['veg'],
      art: { style: 'pizza-margherita' },
      name: { fr: 'Margherita Classica', en: 'Margherita Classica', ar: 'مارغريتا كلاسيكا' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, basilic frais, parmesan et huile d’olive extra vierge.',
        en: 'San Marzano tomato sauce, fior di latte mozzarella, basil, parmesan and extra virgin olive oil.',
        ar: 'صلصة بندورة سان مارزانو، موزاريلا فيور دي لاتيه، ريحان طازج، بارميزان وزيت زيتون بكر.',
      },
    },
    {
      id: 'sujuk-napoli', num: '02', tags: ['spicy'],
      art: { style: 'pizza-sujuk' },
      name: { fr: 'Sujuk Affiné Napoli', en: 'Aged Sujuk Napoli', ar: 'سجق معتّق نابولي' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, sujuk affiné épicé, huile pimentée et basilic frais.',
        en: 'San Marzano tomato sauce, fior di latte, spicy aged sujuk, chili oil and basil.',
        ar: 'صلصة سان مارزانو، فيور دي لاتيه، سجق معتّق حار، زيت الفليفلة الحارة وريحان طازج.',
      },
    },
    {
      id: 'quattro', num: '03', tags: ['veg'],
      art: { style: 'pizza-quattro' },
      name: { fr: 'Quattro Formaggi', en: 'Quattro Formaggi', ar: 'كواترو فورماجي' },
      desc: {
        fr: 'Sauce blanche maison garnie d’un luxueux mélange de fior di latte, gorgonzola, parmesan et fromage fumé affiné.',
        en: 'House white sauce topped with a luxurious blend of fior di latte, gorgonzola, parmesan and aged smoked cheese.',
        ar: 'صلصة بيضاء منزلية مع مزيج فاخر من فيور دي لاتيه والغورغونزولا والبارميزان والجبنة المدخّنة المعتّقة.',
      },
    },
    {
      id: 'musakhan', num: '04', tags: [],
      art: { style: 'pizza-musakhan' },
      name: { fr: 'Musakhan Le Four', en: 'Le Four Musakhan', ar: 'مسخّن لو فور' },
      desc: {
        fr: 'Poulet au sumac, oignons caramélisés, fior di latte, pignons grillés et huile d’olive extra vierge.',
        en: 'Sumac-seasoned chicken, caramelized onions, fior di latte, roasted pine nuts and extra virgin olive oil.',
        ar: 'دجاج بالسمّاق، بصل مكرمل، فيور دي لاتيه، صنوبر محمّص وزيت زيتون بكر ممتاز.',
      },
    },
    {
      id: 'pastrami', num: '05', tags: [],
      art: { style: 'pizza-pastrami' },
      name: { fr: 'Pastrami Bab Touma', en: 'Bab Touma Pastrami', ar: 'باسطرما باب توما' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, pastrami premium, poivrons rouges rôtis, olives noires et oignons.',
        en: 'San Marzano tomato sauce, fior di latte, premium pastrami, roasted red peppers, black olives and onions.',
        ar: 'صلصة سان مارزانو، فيور دي لاتيه، باسطرما فاخرة، فليفلة حمراء مشوية، زيتون أسود وبصل.',
      },
    },
    {
      id: 'shawarma', num: '06', tags: [],
      art: { style: 'pizza-shawarma' },
      name: { fr: 'Shawarma Royale', en: 'Royal Shawarma', ar: 'شاورما رويال' },
      desc: {
        fr: 'Sauce BBQ, fior di latte, poulet shawarma, oignons, sauce à l’ail, mélasse de grenade et roquette fraîche.',
        en: 'BBQ sauce, fior di latte, shawarma chicken, onions, garlic sauce, pomegranate molasses and fresh arugula.',
        ar: 'صلصة باربكيو، فيور دي لاتيه، شاورما دجاج، بصل، ثومية، دبس رمان وجرجير طازج.',
      },
    },
    {
      id: 'damascus-night', num: '07', tags: ['veg'],
      art: { style: 'pizza-falafel' },
      name: { fr: 'Nuit de Damas', en: 'Damascus Night', ar: 'ليلة دمشقية' },
      desc: {
        fr: 'Sauce tahini, falafels croustillants, tomates, cornichons, sauce aux piments, tranches de citron, menthe fraîche et persil.',
        en: 'Tahini sauce, crispy falafel, tomatoes, pickles, pepper sauce, lemon slices, fresh mint and parsley.',
        ar: 'صلصة طحينة، فلافل مقرمشة، بندورة، كبيس، صلصة فليفلة، شرحات ليمون، نعناع طازج وبقدونس.',
      },
    },
    {
      id: 'garden', num: '08', tags: ['veg'],
      art: { style: 'pizza-garden' },
      name: { fr: 'Jardin Le Four', en: 'Le Four Garden', ar: 'جنينة لو فور' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, légumes grillés, olives, champignons et basilic.',
        en: 'San Marzano tomato sauce, fior di latte, grilled vegetables, olives, mushrooms and basil.',
        ar: 'صلصة سان مارزانو، فيور دي لاتيه، خضار مشوية، زيتون، فطر وريحان.',
      },
    },
    {
      id: 'bab-sharqi', num: '09', tags: [],
      art: { style: 'pizza-turkey' },
      name: { fr: 'Bab Sharqi', en: 'Bab Sharqi', ar: 'باب شرقي' },
      desc: {
        fr: 'Sauce tomate San Marzano, fior di latte, champignons, artichauts, olives noires, dinde fumée et fromage fumé affiné.',
        en: 'San Marzano tomato sauce, fior di latte, mushrooms, artichokes, black olives, smoked turkey and aged smoked cheese.',
        ar: 'صلصة سان مارزانو، فيور دي لاتيه، فطر، أرضي شوكي، زيتون أسود، حبش مدخّن وجبنة مدخّنة معتّقة.',
      },
    },
    {
      id: 'marinara', num: '10', tags: ['veg'],
      art: { style: 'pizza-marinara' },
      name: { fr: 'De Damas à Napoli', en: 'Damas to Napoli', ar: 'من دمشق إلى نابولي' },
      desc: {
        fr: 'Sauce tomate San Marzano, ail frais, origan, basilic et huile d’olive extra vierge.',
        en: 'San Marzano tomato sauce, fresh garlic, oregano, basil and extra virgin olive oil.',
        ar: 'صلصة سان مارزانو، ثوم طازج، أوريغانو، ريحان وزيت زيتون بكر ممتاز.',
      },
    },
  ],

  minis: [
    { id: 'mini-spinach', price: 15, tags: ['veg'], art: { style: 'mini', ink: '#46522A' },
      name: { fr: 'Mini Épinards', en: 'Mini Spinach', ar: 'ميني سبانخ' },
      desc: { fr: 'Douze petits triangles aux épinards, format bouchée.', en: 'Twelve bite-size spinach triangles.', ar: 'اثنتا عشرة لقمة مثلثات سبانخ.' } },
    { id: 'mini-sfiha', price: 17, tags: [], art: { style: 'mini', ink: '#8A4A38' },
      name: { fr: 'Mini Sfiha', en: 'Mini Sfiha', ar: 'ميني صفيحة' },
      desc: { fr: 'Douze petites sfihas au bœuf, bien dorées.', en: 'Twelve golden baked meat sfihas.', ar: 'اثنتا عشرة صفيحة لحمة مذهّبة بالفرن.' } },
    { id: 'mini-pizza', price: 15, tags: [], art: { style: 'mini', ink: '#B14A3A' },
      name: { fr: 'Mini Pizza', en: 'Mini Pizza', ar: 'ميني بيتزا' },
      desc: { fr: 'Douze petites pizzas moelleuses.', en: 'Twelve soft little pizzas.', ar: 'اثنتا عشرة بيتزا صغيرة هشّة.' } },
    { id: 'mini-sujuk', price: 18, tags: ['spicy'], art: { style: 'mini', ink: '#6A2D34' },
      name: { fr: 'Mini Sujuk', en: 'Mini Sujuk', ar: 'ميني سجق' },
      desc: { fr: 'Douze bouchées au sujuk épicé.', en: 'Twelve spicy sujuk bites.', ar: 'اثنتا عشرة لقمة بالسجق الحار.' } },
    { id: 'mini-musakhan', price: 17, tags: [], art: { style: 'mini', ink: '#B79B5B' },
      name: { fr: 'Mini Poulet Musakhan', en: 'Mini Chicken Musakhan', ar: 'ميني مسخّن دجاج' },
      desc: { fr: 'Douze petits rouleaux de poulet au sumac.', en: 'Twelve sumac chicken rolls.', ar: 'اثنتا عشرة لفافة دجاج بالسمّاق.' } },
    { id: 'mini-olive', price: 15, tags: ['veg'], art: { style: 'mini', ink: '#6E7A35' },
      name: { fr: 'Mini Olives', en: 'Mini Olive', ar: 'ميني زيتون' },
      desc: { fr: 'Douze bouchées aux olives.', en: 'Twelve Levantine olive bites.', ar: 'اثنتا عشرة لقمة بزيتون بلاد الشام.' } },
    { id: 'mini-cheese', price: 17, tags: ['veg'], art: { style: 'mini', ink: '#D9A94E' },
      name: { fr: 'Mini Fromage', en: 'Mini Cheese', ar: 'ميني جبنة' },
      desc: { fr: 'Douze bouchées au fromage fondant.', en: 'Twelve melty cheese bites.', ar: 'اثنتا عشرة لقمة بالجبنة الذائبة.' } },
    { id: 'mini-hotdog', price: 15, tags: [], art: { style: 'mini', ink: '#7A4632' },
      name: { fr: 'Mini Hot-Dog', en: 'Mini Hot Dog', ar: 'ميني هوت دوغ' },
      desc: { fr: 'Douze petits roulés au hot-dog.', en: 'Twelve soft hot dog rolls.', ar: 'اثنتا عشرة لفافة هوت دوغ طرية.' } },
  ],

  mezze: [
    { id: 'hummus', price: 7, tags: ['veg'], art: { style: 'bowl', ink: '#E8D9BD', accent: '#6E7A35' },
      name: { fr: 'Hommos', en: 'Hummus', ar: 'حمص' },
      desc: {
        fr: 'Purée de pois chiches crémeuse au tahini et au citron frais, arrosée d’huile d’olive.',
        en: 'Creamy chickpea purée blended with tahini and fresh lemon juice, finished with extra virgin olive oil.',
        ar: 'حمص كريمي بالطحينة وعصير الليمون الطازج، مع رشّة زيت زيتون بكر ممتاز.',
      } },
    { id: 'mutabal', price: 9, tags: ['veg'], art: { style: 'bowl', ink: '#C9B9A6', accent: '#6A2D34' },
      name: { fr: 'Moutabal d’Aubergine', en: 'Eggplant Mutabal', ar: 'متبل باذنجان' },
      desc: {
        fr: 'Aubergine grillée au bon goût fumé, avec tahini, citron et huile d’olive.',
        en: 'Smoky roasted eggplant blended with tahini, fresh lemon juice and extra virgin olive oil.',
        ar: 'باذنجان مشوي بنكهة مدخّنة مع الطحينة وعصير الليمون وزيت الزيتون البكر.',
      } },
    { id: 'muhamara-dip', price: 9, tags: ['veg', 'spicy'], art: { style: 'bowl', ink: '#B14A3A', accent: '#B79B5B' },
      name: { fr: 'Mouhammara', en: 'Muhammara', ar: 'محمرة' },
      desc: {
        fr: 'Poivrons rouges rôtis, noix et mélasse de grenade. Riche et juste assez relevé.',
        en: 'A rich blend of roasted red peppers, walnuts and pomegranate molasses, finished with extra virgin olive oil.',
        ar: 'مزيج غني من الفليفلة الحمراء المشوية والجوز ودبس الرمان، مع لمسة زيت زيتون بكر.',
      } },
  ],

  drinks: [
    { id: 'cafe', price: null, tags: [], art: { style: 'cup' },
      name: { fr: 'Café', en: 'Coffee', ar: 'قهوة' },
      desc: { fr: 'Bien chaud, préparé comme au pays.', en: 'Freshly brewed, the way back home.', ar: 'محضّرة طازجة على الأصول.' } },
    { id: 'the', price: null, tags: [], art: { style: 'cup' },
      name: { fr: 'Thé', en: 'Tea', ar: 'شاي' },
      desc: { fr: 'Thé chaud, infusé à la demande.', en: 'Hot tea brewed to order.', ar: 'شاي ساخن يُحضّر عند الطلب.' } },
    { id: 'ayran', price: null, tags: [], art: { style: 'glass' },
      name: { fr: 'Ayran', en: 'Ayran', ar: 'عيران' },
      desc: { fr: 'Boisson au yogourt, fraîche et légèrement salée.', en: 'Chilled yogurt drink, lightly salted.', ar: 'شراب اللبن المنعش بلمسة ملح.' } },
    { id: 'jus', price: null, tags: [], art: { style: 'bottle' },
      name: { fr: 'Jus', en: 'Juice', ar: 'عصير' },
      desc: { fr: 'Un choix de jus de fruits.', en: 'A selection of fruit juices.', ar: 'تشكيلة من عصائر الفواكه.' } },
    { id: 'soda', price: null, tags: [], art: { style: 'can' },
      name: { fr: 'Boisson gazeuse', en: 'Soft drink', ar: 'مشروب غازي' },
      desc: { fr: 'Un choix de boissons gazeuses.', en: 'A selection of soft drinks.', ar: 'تشكيلة من المشروبات الغازية.' } },
    { id: 'eau', price: null, tags: [], art: { style: 'bottle' },
      name: { fr: 'Eau', en: 'Water', ar: 'مياه' },
      desc: { fr: 'Eau plate ou pétillante.', en: 'Still or sparkling water.', ar: 'مياه عادية أو غازية.' } },
  ],
};

/* ── coordonnées & liens officiels (source unique) ───────── */
const INFO = {
  phoneDisplay: '(514) 624-3330',
  phoneRaw: '15146243330',
  whatsapp: '15146243330',
  email: 'info@lefourboulangerie.com',
  address: '15708 Boul. de Pierrefonds, Pierrefonds, QC H9H 3P6',
  maps: 'https://maps.app.goo.gl/gFnkbYyCMBkVqM2t5',
  dir: 'https://www.google.com/maps/dir/?api=1&destination=Bakery+Le+Four,+15708+Boulevard+Pierrefonds,+Pierrefonds,+QC+H9H+3P6',
  review: 'https://maps.google.com/?cid=7994750746587991686',
  uber: 'https://www.ubereats.com/ca/store/boulangerie-le-four/Sk5_leiLW6CDvsTvThUTWw',
  doordash: 'https://www.doordash.com/store/bakery-le-four-montreal-26133532/',
  instagram: 'https://www.instagram.com/lefourboulangerie/',
  facebook: 'https://www.facebook.com/boulangerielefour/',
  /* collez ici votre Stripe Payment Link (Dashboard → Payment Links)
     pour activer le bouton « Payer en ligne » : */
  stripe: '',
};

/* Horaires machine (heure de Montreal) — confirmes par le client :
   dim 6 h 30 a 15 h · lun ferme · mar-jeu et sam 6 h 30 a 17 h · ven 6 h 30 a 15 h.
   Index: 0=dim … 6=sam. [ouverture, fermeture] en minutes depuis minuit. */
const SCHEDULE = {
  0: [390, 900],
  1: null,
  2: [390, 1020],
  3: [390, 1020],
  4: [390, 1020],
  5: [390, 900],
  6: [390, 1020],
};